version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: SkipPay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PetrSkipPay2024!
  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
